# Main azure-pipelines config file

jobs:
  # "build" job - run on all branches
  - job: build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: all-images.yml
        parameters:
          command: build

  # push job - runs only on master
  - job: build_and_push
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
    pool:
      vmImage: "ubuntu-latest"
    steps:

      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: docker-hub
      
      - template: all-images.yml
        parameters:
          command: buildAndPush
