jobs:
  - job: "OpenXR_Spec"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: build-template.yml
        parameters:
          tag: openxr-base

      - template: build-template.yml
        parameters:
          tag: openxr

  - job: "OpenXR_SDK"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: build-template.yml
        parameters:
          tag: openxr-sdk

  - job: "OpenXR_Pregenerated_SDK"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: build-template.yml
        parameters:
          tag: openxr-pregenerated-sdk-base

      - template: build-template.yml
        parameters:
          tag: openxr-pregenerated-sdk

  # This image build is broken right now: E: Package 'ttf-lyx' has no installation candidate
  # - job: "Vulkan"
  #   pool:
  #     vmImage: "ubuntu-latest"
  #   steps:
  #     - template: build-template.yml
  #       parameters:
  #         tag: latest

  - job: "Push"
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
    dependsOn:
      - OpenXR_Spec
      - OpenXR_SDK
      - OpenXR_Pregenerated_SDK
      # - Vulkan
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: "Docker Hub as rpavlik"

      - template: build-template.yml
        parameters:
          command: push
          tag: openxr-base

      - template: build-template.yml
        parameters:
          command: push
          tag: openxr

      - template: build-template.yml
        parameters:
          command: push
          tag: openxr-sdk

      - template: build-template.yml
        parameters:
          command: push
          tag: openxr-pregenerated-sdk-base

      - template: build-template.yml
        parameters:
          command: push
          tag: openxr-pregenerated-sdk

      # - template: build-template.yml
      #   parameters:
      #     command: push
      #     tag: latest
